---
sudo: required
language: generic
services:
  - docker
env:
  jobs:
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"
    - image="ubuntu" tag="xenial"
before_install:
  - sudo apt-get -qq update
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
