---
- name: Verify
  hosts: all
  become: no
  gather_facts: no

  tasks:
    - name: Load role variables.
      include_vars:
        file: "../../vars/main.yml"

    - name: Load role variables.
      include_vars:
        file: "../../defaults/main.yml"

    - name: Confirm installed version is correct
      shell: >
        set -o pipefail &&
        "{{ go_install_prefix }}/go/bin/go" version |
        grep -F "{{ go_version }}"
      args:
        executable: /bin/bash
      register: go_version_test
      failed_when: go_version_test.rc != 0
      changed_when: false
